### ISSUE TITLE
Support for Sphinx 4

### ISSUE THREAD

**Issue by fish-train** [sphinx-contrib/images#24]
I upgraded Sphinx. Now i had version 4.

There is mistake, when i make html:

`Extension error (sphinxcontrib.images):                                                                                                                               
Handler <function install_backend_static_files at 0x046DD1E0> for event 'env-updated' threw an exception (exception: 'Sphinx' object has no attribute 'add_stylesheet')`

**Comment by SilverRainZ** [comment]
What version of sphinxcontrib.images are you using? I think the latest version works well under Sphinx4.

**Comment by fish-train** [comment]
@SilverRainZ could you help me please, how to see sphinxcontrib.images version?

**Comment by SilverRainZ** [comment]
> @SilverRainZ could you help me please, how to see sphinxcontrib.images version?

```pip show sphinxcontrib-images```

**Comment by fish-train** [comment]
0.9.2

How i can upgrade extension?

**Comment by SilverRainZ** [comment]
I think it would be better to google it before asking here.

For this question: `pip install --upgrade sphinxcontrib-images`.

**Comment by jonascj** [comment]
Version 0.9.3 is correctly working with Sphinx 4 (tested with sphinx 4.0.2), but version 0.9.2 is not working with Sphinx4.

The reason being https://github.com/sphinx-contrib/images/pull/12 was not included in release 0.9.2. 

I don't think we can change version 0.9.2 requirements not, but back then we could have required Sphinx versions 3.x or below, hence users of 0.9.2 and 0.9.1 would get an error if they upgraded Sphinx to 4.x or if they did `pip install sphinxcontrib-images` they would get a compatible version of Sphinx installed (not 4.x, but 2.x or 3.x).
