### ISSUE TITLE
0.9.5rc1 AttributeError: 'function' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by TriangleBear** [sphinx-contrib/images#45]
The `0.9.5rc1` build is getting a scary AttributeError, which I don't recognize.

```
AttributeError: 'function' object has no attribute 'startswitch`
. . .
Message: 'lightbox2/dist/css/lightbox.min/css'
Arguments: ()
```

Keeps repeating 9 times for some reason.

Is this related to something or is it because of the build?

**Comment by jonascj** [comment]
@TriangleBear Thank you for reporting your observation. When do you encounter it, could you provide a complete console session log (commands + output)? Maybe an example sphinx-project which will produce these errors upon invoking `make html`.

If it is a Python error then it sounds like a typo - there is a `startswith` method on string objects, testing for a certain string at the beginning of another string. The string `startswitch` however does not appear anywhere in the source tree ...

**Comment by TriangleBear** [comment]
Gotcha, I'll providing the error as soon as possible.

**Comment by jonascj** [comment]
I've confirmed this, although I find the error to be `AttributeError: 'function' object has no attribute 'startswith'` (so I've changed the title of your issue).

It appears the last commit of sphinx to work with sphinxcontrib.images 0.9.5rc1 is `dd7a00dfb558095f6d6261daa23bdc37eeffece3`.

Sphinx  `a56fdad70bbabb8b8c35d7640275a2ed607d786a` is unable to import sphinxcontrib.images: 

    Extension error:
    Could not import extension sphinxcontrib.images (exception: cannot import name 'brown' from 'sphinx.util.console' (/tmp/bisect/sphinx/sphinx/util/console.py))

At a later commit sphinxcontrib.images must become importable again so we can get the `no attribute 'startswith'`-error. I'll hunt this commit tomorrow.

**Comment by jonascj** [comment]
The first commit to throw the `AttributeError: 'function' object has no attribute 'startswith'` is  7154672c2ed9496cc639584171ea80f1e7b0f6f7. 

Between  that commit (7154672c) and the last commit to work with 0.9.5rc1 (dd7a00dfb558) different errors are seen.

**Comment by jonascj** [comment]
And in the in the end maybe we should just use `'brown'` instead of `brown` from `from sphinx.util.console import brown`, as suggested by @j9ac9k. This works for all tests suggested by #41: https://github.com/sphinx-contrib/images/actions/runs/14478814881

**Comment by TriangleBear** [comment]
Thank you very much @jonascj

**Comment by TriangleBear** [comment]
Right now, it does not have any errors or warnings. I'll further test this while working on my own documentation.

**Comment by TriangleBear** [comment]
it's having a bit of problem right now while I'm testing it, or maybe I'm not in the right branch.

The AttributeError in my fork is back.
https://github.com/TriangleBear/images

**Comment by jonascj** [comment]
Yes, you only have the master branch in your fork. Until I hopefully make a release by the end of the weekend (and everything will be in master) you can use / have a look at https://github.com/sphinx-contrib/images/tree/pr3941_color_fix or https://github.com/sphinx-contrib/images/commits/release-1.0.0/

**Comment by shareefj** [comment]
Is it possible to maintain known working versions of sphinx and sphinx-contrib.images on the home page?  I'm going from one bug report to the next as I try to build my docs.

**Comment by t-b** [comment]
@shareefj I'm using

```
breathe==4.35.0
sphinx==7.3.7
sphinxcontrib-fulltoc==1.2
sphinxcontrib-images==0.9.4
sphinxcontrib-youtube==1.2.0
```

successfully since more than a year.
